FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git

COPY . /repo
WORKDIR /repo/src
RUN make -j8

RUN mkdir -p /deps
RUN ldd /repo/build/bin/dumpBlob | tr -s '[:blank:]' '\n' | grep '^/' | xargs -I % sh -c 'cp % /deps;'

FROM ubuntu:22.04 as package

COPY --from=builder /deps /deps
COPY --from=builder /repo/build/bin/dumpBlob /repo/build/bin/dumpBlob
ENV LD_LIBRARY_PATH=/deps
